# Generated by Django 5.0.6 on 2024-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=100)),
                ('ipk', models.FloatField()),
                ('semester', models.IntegerField()),
                ('organisasi', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('asal_kota', models.CharField(max_length=50)),
                ('sks_diambil', models.IntegerField()),
                ('lama_studi', models.IntegerField()),
                ('jalur_masuk', models.CharField(max_length=20)),
                ('tahun_masuk', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
